### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by MacBook-Pro-gala** [nexuslrf/SPIDR#12]
python train_ft.py --config ../dev_scripts/spidr/lego.ini --run_mode=sdf

xyz_world_all torch.Size([91388555, 3]) torch.Size([91388555, 1]) torch.Size([91388555])
%%%%%%%%%%%%%  getattr(dataset, spacemin, None) None
vishull_mask torch.Size([91388555])
alpha masking xyz_world_all torch.Size([68219605, 3]) torch.Size([68219605, 1])
xyz_residual torch.Size([68219605])
min_idx torch.Size([1079024])
after voxelize: torch.Size([1079024, 3]) torch.Size([1079024, 1])
  0%|                                                                                                           | 0/549 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_ft.py", line 679, in <module>
    main()
  File "train_ft.py", line 146, in main
    img_lst, c2ws_lst, w2cs_lst, intrinsics_all, HDWD_lst = gen_points_filter_embeddings(train_dataset, visualizer, opt)
  File "/code/oldSPIDR/SPIDR/run/ft_helper.py", line 111, in gen_points_filter_embeddings
    model.query_embedding(HDWD_lst[i], torch.as_tensor(cam_xyz_all[i][None, ...], device="cuda", dtype=torch.float32), 
  File "/code/oldSPIDR/SPIDR/run/../models/mvs_points_volumetric_model.py", line 321, in query_embedding
    return self.net_mvs.query_embedding(HDWD, cam_xyz, photometric_confidence, img_feats, c2ws, w2cs, intrinsics, cam_vid, pointdir_w=pointdir_w)
  File "/code/oldSPIDR/SPIDR/run/../models/mvs/mvs_points_model.py", line 240, in query_embedding
    _, view_ids = feat_str.split("_")
ValueError: too many values to unpack (expected 2)
end loading

**Comment by liuyuwan233** [comment]
Hi！
I had the same problem as you. I solved this problem by rewrting this setting "appr_feature_str0 = [imgfeat_0_0123, dir_0, point_conf]" in the ../dev_scripts/w_n360/lego.ini.
I hope this helps you.
